/**
 * IPTV Bookmarklet — Scrape ajobtv.com tokens & push to GitHub Gist
 * 
 * This file is the READABLE version of the bookmarklet.
 * The actual bookmarklet is a minified javascript: URL generated by bookmarklet_setup.html
 * 
 * How it works:
 * 1. Runs inside ajobtv.com page context (no CORS issues)
 * 2. Extracts the `channels` array from the page's JavaScript
 * 3. Generates M3U playlist
 * 4. Pushes to GitHub Gist via API
 */

(function() {
    // ===== CONFIG (injected by setup page) =====
    var GIST_ID = '__GIST_ID__';
    var GITHUB_TOKEN = '__GITHUB_TOKEN__';

    // ===== TOAST NOTIFICATION =====
    function showToast(msg, isError) {
        var existing = document.getElementById('iptv-toast');
        if (existing) existing.remove();
        
        var toast = document.createElement('div');
        toast.id = 'iptv-toast';
        toast.style.cssText = 'position:fixed;top:20px;left:50%;transform:translateX(-50%);' +
            'padding:14px 24px;border-radius:12px;color:#fff;font-size:15px;font-weight:600;' +
            'z-index:999999;font-family:sans-serif;text-align:center;max-width:90vw;' +
            'box-shadow:0 8px 32px rgba(0,0,0,0.3);backdrop-filter:blur(10px);' +
            'animation:slideDown 0.3s ease;' +
            (isError ? 'background:rgba(220,53,69,0.95);' : 'background:rgba(40,167,69,0.95);');
        toast.textContent = msg;
        
        // Add animation keyframes
        var style = document.createElement('style');
        style.textContent = '@keyframes slideDown{from{opacity:0;transform:translateX(-50%) translateY(-20px)}to{opacity:1;transform:translateX(-50%) translateY(0)}}';
        document.head.appendChild(style);
        
        document.body.appendChild(toast);
        setTimeout(function() { toast.remove(); style.remove(); }, 5000);
    }

    // ===== EXTRACT CHANNELS =====
    function extractChannels() {
        // Method 1: Try to access the global `channels` variable directly
        // ajobtv.com defines it as: const channels = [...]
        // Since bookmarklet runs in the page context, we can try to find it
        
        // The channels are defined inside a DOMContentLoaded listener,
        // so they're scoped. We need to extract from the HTML source instead.
        var scripts = document.querySelectorAll('script');
        var channelsData = null;
        
        for (var i = 0; i < scripts.length; i++) {
            var text = scripts[i].textContent || scripts[i].innerText || '';
            // Look for the channels array definition
            var match = text.match(/const\s+channels\s*=\s*(\[[\s\S]*?\]);\s*\n/);
            if (!match) {
                match = text.match(/var\s+channels\s*=\s*(\[[\s\S]*?\]);\s*\n/);
            }
            if (!match) {
                match = text.match(/let\s+channels\s*=\s*(\[[\s\S]*?\]);\s*\n/);
            }
            if (match) {
                try {
                    channelsData = JSON.parse(match[1]);
                    break;
                } catch(e) {
                    // Try with a more relaxed approach — the JSON might have trailing issues
                    try {
                        channelsData = (new Function('return ' + match[1]))();
                        break;
                    } catch(e2) {
                        console.log('Parse error:', e2);
                    }
                }
            }
        }
        
        // Method 2: If no inline script found, extract from channel-card data attributes
        if (!channelsData || channelsData.length === 0) {
            var cards = document.querySelectorAll('.channel-card[data-url]');
            if (cards.length > 0) {
                channelsData = [];
                cards.forEach(function(card) {
                    var url = card.getAttribute('data-url') || '';
                    var name = card.getAttribute('data-name') || 'Unknown';
                    var img = card.querySelector('img');
                    var logo = '';
                    if (img) {
                        var src = img.getAttribute('src') || '';
                        // Extract just the filename from the src
                        logo = src.split('/').pop();
                    }
                    if (url) {
                        channelsData.push({
                            name: name,
                            play_url: url,
                            logo: logo,
                            category_name: 'Live TV'
                        });
                    }
                });
            }
        }
        
        return channelsData;
    }

    // ===== GENERATE M3U =====
    function generateM3U(channels) {
        var m3u = '#EXTM3U\n';
        
        channels.forEach(function(ch) {
            var name = (ch.name || 'Unknown').trim();
            var playUrl = (ch.play_url || '').replace(/\\\//g, '/');
            var logo = ch.logo || '';
            var category = ch.category_name || 'Live TV';
            
            if (!playUrl) return;
            
            // Ensure remote=no_check_ip is present
            if (playUrl.indexOf('token=') !== -1 && playUrl.indexOf('remote=') === -1) {
                var sep = playUrl.indexOf('?') !== -1 ? '&' : '?';
                playUrl += sep + 'remote=no_check_ip';
            }
            
            // Build logo URL
            var logoUrl = '';
            if (logo) {
                if (logo.indexOf('http') === 0) {
                    logoUrl = logo;
                } else {
                    logoUrl = 'https://ajobtv.com/assets/images/channels/' + logo;
                }
            }
            
            var logoPart = logoUrl ? ' tvg-logo="' + logoUrl + '"' : '';
            var chId = name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
            
            m3u += '#EXTINF:-1 tvg-id="' + chId + '"' + logoPart + 
                   ' tvg-name="' + name + '" group-title="' + category + '",' + name + '\n';
            m3u += playUrl + '\n';
        });
        
        return m3u;
    }

    // ===== GENERATE CHANNELS JSON =====
    function generateChannelsJSON(channels) {
        var result = [];
        
        channels.forEach(function(ch) {
            var name = (ch.name || 'Unknown').trim();
            var playUrl = (ch.play_url || '').replace(/\\\//g, '/');
            var logo = ch.logo || '';
            var category = ch.category_name || 'Live TV';
            
            if (!playUrl) return;
            
            if (playUrl.indexOf('token=') !== -1 && playUrl.indexOf('remote=') === -1) {
                var sep = playUrl.indexOf('?') !== -1 ? '&' : '?';
                playUrl += sep + 'remote=no_check_ip';
            }
            
            var chId = name.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
            
            result.push({
                id: chId,
                name: name,
                logo: logo,
                url: playUrl,
                category: category,
                scraped_at: Math.floor(Date.now() / 1000)
            });
        });
        
        // Add default 4K channels
        var existingIds = {};
        result.forEach(function(ch) { existingIds[ch.id] = true; });
        
        var default4K = [
            {
                id: 'golive_4k',
                name: 'GoLive 4K',
                logo: 'https://img.icons8.com/color/144/4k-resolution.png',
                url: 'http://203.18.159.180/GoLIve/index.m3u8',
                category: '4K',
                scraped_at: Math.floor(Date.now() / 1000)
            },
            {
                id: 'hdr_4k',
                name: 'HDR 4K',
                logo: 'https://img.icons8.com/color/144/4k-resolution.png',
                url: 'https://go8knm.optikl.ink/OT/live/HDR/HDR/1950411.m3u8',
                category: '4K',
                scraped_at: Math.floor(Date.now() / 1000)
            }
        ];
        
        default4K.forEach(function(ch) {
            if (!existingIds[ch.id]) {
                result.push(ch);
            }
        });
        
        return result;
    }

    // ===== PUSH TO GIST =====
    function updateGist(m3uData, channelsJSON) {
        showToast('⏳ Pushing to Gist...');
        
        var payload = {
            description: 'Velocity IPTV Live M3U Playlist - Auto Updated',
            files: {
                'playlist.m3u': { content: m3uData },
                'playlist.m3u8': { content: m3uData },
                'channels.json': { content: JSON.stringify(channelsJSON, null, 2) }
            }
        };
        
        fetch('https://api.github.com/gists/' + GIST_ID, {
            method: 'PATCH',
            headers: {
                'Authorization': 'token ' + GITHUB_TOKEN,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(payload)
        })
        .then(function(response) {
            if (!response.ok) {
                throw new Error('HTTP ' + response.status);
            }
            return response.json();
        })
        .then(function(data) {
            showToast('✅ Playlist updated! ' + channelsJSON.length + ' channels pushed to Gist');
        })
        .catch(function(err) {
            showToast('❌ Failed: ' + err.message, true);
        });
    }

    // ===== MAIN =====
    try {
        // Check we're on ajobtv.com
        if (window.location.hostname.indexOf('ajobtv') === -1) {
            showToast('❌ Open ajobtv.com first, then tap this bookmarklet!', true);
            return;
        }
        
        showToast('🔄 Extracting channels...');
        
        var channels = extractChannels();
        
        if (!channels || channels.length === 0) {
            showToast('❌ No channels found on this page!', true);
            return;
        }
        
        var m3u = generateM3U(channels);
        var channelsJSON = generateChannelsJSON(channels);
        
        // Also generate M3U for the 4K channels (they're already in channelsJSON)
        var m3uWith4K = generateM3U(channels);
        // Append 4K to M3U
        var default4K = [
            { name: 'GoLive 4K', play_url: 'http://203.18.159.180/GoLIve/index.m3u8', logo: 'https://img.icons8.com/color/144/4k-resolution.png', category_name: '4K' },
            { name: 'HDR 4K', play_url: 'https://go8knm.optikl.ink/OT/live/HDR/HDR/1950411.m3u8', logo: 'https://img.icons8.com/color/144/4k-resolution.png', category_name: '4K' }
        ];
        var existingNames = {};
        channels.forEach(function(ch) { existingNames[(ch.name||'').toLowerCase()] = true; });
        default4K.forEach(function(ch) {
            if (!existingNames[ch.name.toLowerCase()]) {
                m3uWith4K += '#EXTINF:-1 tvg-id="' + ch.name.toLowerCase().replace(/[^a-z0-9]+/g,'_') + 
                    '" tvg-logo="' + ch.logo + '" tvg-name="' + ch.name + 
                    '" group-title="' + ch.category_name + '",' + ch.name + '\n' + ch.play_url + '\n';
            }
        });
        
        updateGist(m3uWith4K, channelsJSON);
        
    } catch(e) {
        showToast('❌ Error: ' + e.message, true);
    }
})();
